Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
# Style/StringLiterals:
  # EnforcedStyle: double_quotes
Style/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Guardfile'
    - 'Gemfile'
    - 'schema.rb'
